// Curated set of well-known public companies used to compute the "Most
// Covered" panel — see lib/mostCovered.js. This is a heuristic keyword
// match against article titles, not real entity extraction, so aliases are
// picked to be specific enough to avoid obvious false positives (e.g. "Ford
// Motor" instead of bare "Ford", which is also a common surname/place).
export const TRACKED_COMPANIES = [
  { name: "Apple", ticker: "AAPL", aliases: ["Apple"] },
  { name: "Microsoft", ticker: "MSFT", aliases: ["Microsoft"] },
  { name: "Amazon", ticker: "AMZN", aliases: ["Amazon"] },
  { name: "Alphabet", ticker: "GOOGL", aliases: ["Alphabet", "Google"] },
  { name: "Meta", ticker: "META", aliases: ["Meta Platforms", "Facebook"] },
  { name: "Tesla", ticker: "TSLA", aliases: ["Tesla"] },
  { name: "Nvidia", ticker: "NVDA", aliases: ["Nvidia"] },
  { name: "Netflix", ticker: "NFLX", aliases: ["Netflix"] },
  { name: "Berkshire Hathaway", ticker: "BRK.B", aliases: ["Berkshire Hathaway"] },
  { name: "JPMorgan Chase", ticker: "JPM", aliases: ["JPMorgan", "JP Morgan"] },
  { name: "Goldman Sachs", ticker: "GS", aliases: ["Goldman Sachs"] },
  { name: "Morgan Stanley", ticker: "MS", aliases: ["Morgan Stanley"] },
  { name: "Bank of America", ticker: "BAC", aliases: ["Bank of America"] },
  { name: "Wells Fargo", ticker: "WFC", aliases: ["Wells Fargo"] },
  { name: "Visa", ticker: "V", aliases: ["Visa Inc"] },
  { name: "Mastercard", ticker: "MA", aliases: ["Mastercard"] },
  { name: "PayPal", ticker: "PYPL", aliases: ["PayPal"] },
  { name: "Disney", ticker: "DIS", aliases: ["Walt Disney", "Disney"] },
  { name: "Boeing", ticker: "BA", aliases: ["Boeing"] },
  { name: "Intel", ticker: "INTC", aliases: ["Intel"] },
  { name: "AMD", ticker: "AMD", aliases: ["Advanced Micro Devices", "AMD"] },
  { name: "IBM", ticker: "IBM", aliases: ["IBM"] },
  { name: "Oracle", ticker: "ORCL", aliases: ["Oracle"] },
  { name: "Salesforce", ticker: "CRM", aliases: ["Salesforce"] },
  { name: "Walmart", ticker: "WMT", aliases: ["Walmart"] },
  { name: "Costco", ticker: "COST", aliases: ["Costco"] },
  { name: "Starbucks", ticker: "SBUX", aliases: ["Starbucks"] },
  { name: "McDonald's", ticker: "MCD", aliases: ["McDonald's", "McDonalds"] },
  { name: "Coca-Cola", ticker: "KO", aliases: ["Coca-Cola", "Coca Cola"] },
  { name: "ExxonMobil", ticker: "XOM", aliases: ["ExxonMobil", "Exxon Mobil", "Exxon"] },
  { name: "Chevron", ticker: "CVX", aliases: ["Chevron"] },
  { name: "Pfizer", ticker: "PFE", aliases: ["Pfizer"] },
  { name: "Johnson & Johnson", ticker: "JNJ", aliases: ["Johnson & Johnson"] },
  { name: "UnitedHealth", ticker: "UNH", aliases: ["UnitedHealth"] },
  { name: "Ford Motor", ticker: "F", aliases: ["Ford Motor"] },
  { name: "General Motors", ticker: "GM", aliases: ["General Motors"] },
  { name: "Uber", ticker: "UBER", aliases: ["Uber"] },
  { name: "Airbnb", ticker: "ABNB", aliases: ["Airbnb"] },
  { name: "Alibaba", ticker: "BABA", aliases: ["Alibaba"] },
];
