export const themes = {
  default: {
    primary: "var(--dark-blue)",
    primaryContrast: "#ffffff",
    secondaryContrast: "var(--secondary-blue)",
    titleContrast: "#eba613ff",
    background: "#ffffff",
    cardBackground: "var(--white)",
    text: "var(--white)",
    textSecondary: "#666666",
    textTertiary: "#181818ff",
    border: "#e0e0e0",
    warning: "#C53030",
  },
  dark: {
    primary: "#1a1a1aff",
    primaryContrast: "var(--white)",
    secondaryContrast: "var(--secondary-blue)",
    titleContrast: "#eba613ff",
    background: "#282c34",
    cardBackground: "#000000ff",
    text: "#f5f5f5ff",
    textSecondary: "#bbbbbb",
    textTertiary: "#181818ff",
    border: "#4a4f5a",
    warning: "#C53030",
  },
};
